"""Recommendation models for KrishiMitra-AI."""

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class RecommendationPriority(StrEnum):
    """Priority levels for agricultural recommendations."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class RecommendationCategory(StrEnum):
    """Agricultural recommendation categories."""

    IRRIGATION = "irrigation"
    FERTILIZER = "fertilizer"
    DISEASE = "disease"
    PEST = "pest"
    WEATHER = "weather"
    CROP = "crop"
    SOIL = "soil"
    SUSTAINABILITY = "sustainability"
    GENERAL = "general"


class Recommendation(BaseModel):
    """Actionable recommendation generated by the decision system."""

    model_config = ConfigDict(extra="forbid")

    recommendation_id: UUID

    category: RecommendationCategory
    priority: RecommendationPriority

    title: str = Field(min_length=1, max_length=200)
    action: str = Field(min_length=1)
    reason: str = Field(min_length=1)

    confidence: float = Field(ge=0.0, le=1.0)

    requires_confirmation: bool = False
    safety_note: str | None = None

    evidence: list[str] = Field(default_factory=list)


__all__ = [
    "Recommendation",
    "RecommendationCategory",
    "RecommendationPriority",
]