from __future__ import annotations

from .citations import (
    Citation,
    CitationBuilder,
    CitationError,
    deduplicate_citations,
    format_citation,
    format_citations,
)
from .embeddings import (
    EmbeddingGenerationError,
    EmbeddingGenerator,
    EmbeddingModel,
    EmbeddingModelError,
    EmbeddingModelInfo,
    EmbeddingModelValidator,
    GeneratedEmbedding,
    EmbeddingBatch,
    ValidatedEmbeddingModel,
    cosine_similarity,
)
from .evaluation import (
    GroundednessEvaluationError,
    GroundednessEvaluator,
    GroundednessResult,
    RelevanceEvaluationError,
    RelevanceEvaluator,
    RelevanceResult,
    RetrievalEvaluationError,
    RetrievalEvaluationResult,
    RetrievalEvaluator,
    hit_rate_at_k,
    precision_at_k,
    recall_at_k,
)
from .ingestion import (
    DocumentMetadata,
    KnowledgeLoadError,
    KnowledgeLoader,
    KnowledgeLoaderBackend,
    LoadedDocument,
    LocalFileLoader,
    MetadataBuilder,
    MetadataError,
    RAGChunk,
    RAGChunker,
    RAGChunkingError,
    TextCleaner,
    TextCleaningError,
    build_metadata,
    chunk_text,
    clean_text,
    load_local_file,
)
from .knowledge import (
    CropKnowledge,
    CropKnowledgeBase,
    CropKnowledgeError,
    DiseaseKnowledge,
    DiseaseKnowledgeBase,
    DiseaseKnowledgeError,
    FertilizerKnowledge,
    FertilizerKnowledgeBase,
    FertilizerKnowledgeError,
    PestKnowledge,
    PestKnowledgeBase,
    PestKnowledgeError,
    SustainabilityKnowledge,
    SustainabilityKnowledgeBase,
    SustainabilityKnowledgeError,
    create_default_crop_knowledge,
    create_default_disease_knowledge,
    create_default_fertilizer_knowledge,
    create_default_pest_knowledge,
    create_default_sustainability_knowledge,
)
from .retrieval import (
    HybridRetrievalError,
    HybridRetrievalResult,
    HybridRetriever,
    InMemoryVectorStore,
    KeywordRetriever,
    RerankedResult,
    RerankerBackend,
    RerankingError,
    SemanticReranker,
    SemanticRetriever,
    RetrievalDocument,
    RetrievalError,
    RetrievalResult,
    SimpleKeywordRetriever,
    VectorStore,
)

__all__ = [
    # Citations
    "Citation",
    "CitationBuilder",
    "CitationError",
    "deduplicate_citations",
    "format_citation",
    "format_citations",

    # Embeddings
    "EmbeddingBatch",
    "EmbeddingGenerationError",
    "EmbeddingGenerator",
    "EmbeddingModel",
    "EmbeddingModelError",
    "EmbeddingModelInfo",
    "EmbeddingModelValidator",
    "GeneratedEmbedding",
    "ValidatedEmbeddingModel",
    "cosine_similarity",

    # Evaluation
    "GroundednessEvaluationError",
    "GroundednessEvaluator",
    "GroundednessResult",
    "RelevanceEvaluationError",
    "RelevanceEvaluator",
    "RelevanceResult",
    "RetrievalEvaluationError",
    "RetrievalEvaluationResult",
    "RetrievalEvaluator",
    "hit_rate_at_k",
    "precision_at_k",
    "recall_at_k",

    # Ingestion
    "DocumentMetadata",
    "KnowledgeLoadError",
    "KnowledgeLoader",
    "KnowledgeLoaderBackend",
    "LoadedDocument",
    "LocalFileLoader",
    "MetadataBuilder",
    "MetadataError",
    "RAGChunk",
    "RAGChunker",
    "RAGChunkingError",
    "TextCleaner",
    "TextCleaningError",
    "build_metadata",
    "chunk_text",
    "clean_text",
    "load_local_file",

    # Knowledge
    "CropKnowledge",
    "CropKnowledgeBase",
    "CropKnowledgeError",
    "DiseaseKnowledge",
    "DiseaseKnowledgeBase",
    "DiseaseKnowledgeError",
    "FertilizerKnowledge",
    "FertilizerKnowledgeBase",
    "FertilizerKnowledgeError",
    "PestKnowledge",
    "PestKnowledgeBase",
    "PestKnowledgeError",
    "SustainabilityKnowledge",
    "SustainabilityKnowledgeBase",
    "SustainabilityKnowledgeError",
    "create_default_crop_knowledge",
    "create_default_disease_knowledge",
    "create_default_fertilizer_knowledge",
    "create_default_pest_knowledge",
    "create_default_sustainability_knowledge",

    # Retrieval
    "HybridRetrievalError",
    "HybridRetrievalResult",
    "HybridRetriever",
    "InMemoryVectorStore",
    "KeywordRetriever",
    "RerankedResult",
    "RerankerBackend",
    "RerankingError",
    "SemanticReranker",
    "SemanticRetriever",
    "RetrievalDocument",
    "RetrievalError",
    "RetrievalResult",
    "SimpleKeywordRetriever",
    "VectorStore",
]