"""Recommendation service contracts for KrishiMitra-AI."""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class RecommendationType(StrEnum):
    """Types of recommendations generated by KrishiMitra."""

    IRRIGATION = "irrigation"
    FERTILIZER = "fertilizer"
    DISEASE_TREATMENT = "disease_treatment"
    PEST_CONTROL = "pest_control"
    CROP = "crop"
    WEATHER_ACTION = "weather_action"
    SUSTAINABILITY = "sustainability"
    GENERAL = "general"


class RecommendationPriority(StrEnum):
    """Priority levels for farmer actions."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class RecommendationContract(BaseModel):
    """Shared recommendation exchanged between KrishiMitra services."""

    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )

    recommendation_id: UUID

    farmer_id: UUID
    farm_id: UUID | None = None
    crop_id: UUID | None = None

    recommendation_type: RecommendationType

    priority: RecommendationPriority = RecommendationPriority.MEDIUM

    title: str = Field(
        min_length=1,
        max_length=200,
    )

    action: str = Field(
        min_length=1,
        max_length=4000,
    )

    rationale: str | None = Field(
        default=None,
        max_length=4000,
    )

    confidence: float = Field(
        ge=0.0,
        le=1.0,
    )

    requires_confirmation: bool = False

    safety_notice: str | None = Field(
        default=None,
        max_length=2000,
    )

    source: str = Field(
        min_length=1,
        max_length=200,
    )

    valid_from: datetime | None = None
    valid_until: datetime | None = None

    created_at: datetime


class RecommendationCreateContract(BaseModel):
    """Contract for creating a recommendation."""

    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )

    farmer_id: UUID

    farm_id: UUID | None = None
    crop_id: UUID | None = None

    recommendation_type: RecommendationType

    priority: RecommendationPriority = RecommendationPriority.MEDIUM

    title: str = Field(
        min_length=1,
        max_length=200,
    )

    action: str = Field(
        min_length=1,
        max_length=4000,
    )

    rationale: str | None = Field(
        default=None,
        max_length=4000,
    )

    confidence: float = Field(
        ge=0.0,
        le=1.0,
    )

    requires_confirmation: bool = False

    safety_notice: str | None = Field(
        default=None,
        max_length=2000,
    )

    source: str = Field(
        min_length=1,
        max_length=200,
    )


__all__ = [
    "RecommendationContract",
    "RecommendationCreateContract",
    "RecommendationPriority",
    "RecommendationType",
]