"""Machine-learning services for KrishiMitra-AI."""

from .common import (
    BaseModelInference,
    ClassificationMetrics,
    Feature,
    FeatureBuilder,
    FeaturePreprocessor,
    InferenceRequest,
    InferenceResult,
    ModelMetadata,
    ModelRegistry,
    RegressionMetrics,
)
from .crop_stage import (
    CropStageClassifier,
    CropStagePrediction,
)
from .disease import (
    DiseaseClassificationResult,
    DiseaseClassifier,
    DiseaseClassifierConfig,
    DiseaseImagePreprocessor,
    DiseaseInferenceService,
    DiseasePrediction,
)
from .energy import (
    EnergyConsumptionCalculator,
    EnergyConsumptionInput,
    EnergyConsumptionResult,
    EnergyPrediction,
    EnergyPredictor,
    PumpModel,
    PumpOperatingPoint,
    PumpPowerResult,
)
from .irrigation import (
    IrrigationFeatureBuilder,
    IrrigationFeatureInput,
    IrrigationPrediction,
    IrrigationPredictor,
    WaterRequirementCalculator,
    WaterRequirementResult,
)
from .pest import (
    PestFeatureBuilder,
    PestFeatureInput,
    PestPrediction,
    PestPredictor,
    PestRiskLevel,
    PestRiskModel,
    PestRiskPrediction,
)
from .training import (
    ClassificationCrossValidationResult,
    ClassificationValidationResult,
    CrossValidator,
    DatasetBuilder,
    DatasetBundle,
    DatasetSplit,
    ExperimentConfig,
    ExperimentResult,
    ExperimentTracker,
    ModelTrainer,
    ModelValidator,
    RegressionCrossValidationResult,
    RegressionValidationResult,
    TrainingResult,
    build_dataset_bundle,
)
from .yield_prediction import (
    YieldFeatureBuilder,
    YieldFeatureInput,
    YieldPrediction,
    YieldPredictor,
    YieldUncertainty,
    YieldUncertaintyEstimator,
)

__all__ = [
    "BaseModelInference",
    "ClassificationCrossValidationResult",
    "ClassificationMetrics",
    "ClassificationValidationResult",
    "CropStageClassifier",
    "CropStagePrediction",
    "CrossValidator",
    "DatasetBuilder",
    "DatasetBundle",
    "DatasetSplit",
    "DiseaseClassificationResult",
    "DiseaseClassifier",
    "DiseaseClassifierConfig",
    "DiseaseImagePreprocessor",
    "DiseaseInferenceService",
    "DiseasePrediction",
    "EnergyConsumptionCalculator",
    "EnergyConsumptionInput",
    "EnergyConsumptionResult",
    "EnergyPrediction",
    "EnergyPredictor",
    "ExperimentConfig",
    "ExperimentResult",
    "ExperimentTracker",
    "Feature",
    "FeatureBuilder",
    "FeaturePreprocessor",
    "InferenceRequest",
    "InferenceResult",
    "IrrigationFeatureBuilder",
    "IrrigationFeatureInput",
    "IrrigationPrediction",
    "IrrigationPredictor",
    "ModelMetadata",
    "ModelRegistry",
    "ModelTrainer",
    "ModelValidator",
    "PestFeatureBuilder",
    "PestFeatureInput",
    "PestPrediction",
    "PestPredictor",
    "PestRiskLevel",
    "PestRiskModel",
    "PestRiskPrediction",
    "PumpModel",
    "PumpOperatingPoint",
    "PumpPowerResult",
    "RegressionCrossValidationResult",
    "RegressionMetrics",
    "RegressionValidationResult",
    "TrainingResult",
    "WaterRequirementCalculator",
    "WaterRequirementResult",
    "YieldFeatureBuilder",
    "YieldFeatureInput",
    "YieldPrediction",
    "YieldPredictor",
    "YieldUncertainty",
    "YieldUncertaintyEstimator",
    "build_dataset_bundle",
]

__version__ = "0.1.0"